### ISSUE TITLE
Keys for commit/reveal should be EC secp256k1 keys

### ISSUE THREAD

**Issue by jmandel** [microsoft/VerifiableCredentials-Verification-SDK-Typescript#54]
When provisioning keys for a commit/reveal pair...

https://github.com/microsoft/VerifiableCredentials-Verification-SDK-Typescript/blob/851f9cfdb1de13190d1ac268f62b578cd30b1371/lib/ApiCrypto/LongFormDid.ts#L99

1. I believe the sidetree implementation [expects](https://github.com/decentralized-identity/sidetree/blob/24f7ded6fd4de6e4f31c5850749f204deded1329/lib/core/versions/0.9.0/util/Jws.ts#L78) these to be `secp256k1` public keys, which wouldn't be compatible with a private `AES-GCM` key

2. It'll be important to return the associated private key (or maybe following the keyStore pattern, write these keys to a relevant store)

**Comment by beejones** [comment]
The longform will be reworked in future iterations. The sidetree longform spec is also changed and the latest spec  is implemented (https://github.com/microsoft/VerifiableCredentials-Verification-SDK-Typescript/commit/5a9b2fb917cbde72ba8f75ed513f6723b330fa37).
